### ISSUE TITLE
System can't install hatch_rest_api, which prevents adding integrations via UI

### ISSUE THREAD

**Issue by brystmar** [dahlb/ha_hatch#68] opened 2023-08-22 22:59 UTC
HACS Hatch Rest Mini Sound Machine v1.16.2
HACS v1.32.1
HACS Frontend: 20220906112053

HA v2023.8.3 (container install)
HA Frontend: 20230802.1 - latest

Just bought a new Hatch Rest+ (2nd gen) and was attempting to add it to Home Assistant.  Added the HACS integration, restarted HA, then waited for everything to load before attempting to add this new integration via the HA UI.  UI spun for a bit, then threw this error message before prompting me for anything:
> Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

I enabled logging as described in the readme, restarted, then pulled up the logs to find errors attempting to install the `hatch_rest_api` package.  I have a suspicion but won't speculate.

```
Logger: homeassistant.util.package
Source: util/package.py:107
First occurred: 15:33:41 (3 occurrences)
Last logged: 15:34:39

Unable to install package hatch_rest_api==1.20.8: error: subprocess-exited-with-error × python setup.py bdist_wheel did not run successfully. │ exit code: 1 ╰─> [68 lines of output] running bdist_wheel running build running build_py creating build creating build/lib.linux-aarch64-cpython-311 creating build/lib.linux-aarch64-cpython-311/awscrt copying awscrt/websocket.py -> build/lib.linux-aarch64-cpython-311/awscrt copying awscrt/io.py -> build/lib.linux-aarch64-cpython-311/awscrt copying awscrt/mqtt5.py -> build/lib.linux-aarch64-cpython-311/awscrt copying awscrt/crypto.py -> build/lib.linux-aarch64-cpython-311/awscrt copying awscrt/common.py -> build/lib.linux-aarch64-cpython-311/awscrt copying awscrt/s3.py -> build/lib.linux-aarch64-cpython-311/awscrt copying awscrt/_test.py -> build/lib.linux-aarch64-cpython-311/awscrt copying awscrt/exceptions.py -> build/lib.linux-aarch64-cpython-311/awscrt copying awscrt/checksums.py -> build/lib.linux-aarch64-cpython-311/awscrt copying awscrt/http.py -> build/lib.linux-aarch64-cpython-311/awscrt copying awscrt/auth.py -> build/lib.linux-aarch64-cpython-311/awscrt copying awscrt/mqtt.py -> build/lib.linux-aarch64-cpython-311/awscrt copying awscrt/__init__.py -> build/lib.linux-aarch64-cpython-311/awscrt creating build/lib.linux-aarch64-cpython-311/awscrt/eventstream copying awscrt/eventstream/rpc.py -> build/lib.linux-aarch64-cpython-311/awscrt/eventstream copying awscrt/eventstream/__init__.py -> build/lib.linux-aarch64-cpython-311/awscrt/eventstream running build_ext Traceback (most recent call last): File "<string>", line 2, in <module> File "<pip-setuptools-caller>", line 34, in <module> File "/tmp/pip-install-zd6bllj3/awscrt_c973741bef8b4ceba1315cb10badacf3/setup.py", line 394, in <module> setuptools.setup( File "/usr/local/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup return distutils.core.setup(**attrs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup return run_commands(dist) ^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands dist.run_commands() File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands self.run_command(cmd) File "/usr/local/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command super().run_command(command) File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command cmd_obj.run() File "/usr/local/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 346, in run self.run_command("build") File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command self.distribution.run_command(command) File "/usr/local/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command super().run_command(command) File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command cmd_obj.run() File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 131, in run self.run_command(cmd_name) File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command self.distribution.run_command(command) File "/usr/local/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command super().run_command(command) File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command cmd_obj.run() File "/tmp/pip-install-zd6bllj3/awscrt_c973741bef8b4ceba1315cb10badacf3/setup.py", line 263, in run self._build_dependencies(dep_build_dir, dep_install_path) File "/tmp/pip-install-zd6bllj3/awscrt_c973741bef8b4ceba1315cb10badacf3/setup.py", line 255, in _build_dependencies self._build_dependencies_impl(build_dir, install_path) File "/tmp/pip-install-zd6bllj3/awscrt_c973741bef8b4ceba1315cb10badacf3/setup.py", line 163, in _build_dependencies_impl cmake = get_cmake_path() ^^^^^^^^^^^^^^^^ File "/tmp/pip-install-zd6bllj3/awscrt_c973741bef8b4ceba1315cb10badacf3/setup.py", line 122, in get_cmake_path raise Exception("CMake must be installed to build from source.") Exception: CMake must be installed to build from source. [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for awscrt ERROR: Could not build wheels for awscrt, which is required to install pyproject.toml-based projects [notice] A new release of pip is available: 23.1.2 -> 23.2.1 [notice] To update, run: pip install --upgrade pip

Unable to install package hatch_rest_api==1.20.8: error: subprocess-exited-with-error × python setup.py bdist_wheel did not run successfully. │ exit code: 1 ╰─> [68 lines of output] running bdist_wheel running build running build_py creating build creating build/lib.linux-aarch64-cpython-311 creating build/lib.linux-aarch64-cpython-311/awscrt copying awscrt/websocket.py -> build/lib.linux-aarch64-cpython-311/awscrt copying awscrt/io.py -> build/lib.linux-aarch64-cpython-311/awscrt copying awscrt/mqtt5.py -> build/lib.linux-aarch64-cpython-311/awscrt copying awscrt/crypto.py -> build/lib.linux-aarch64-cpython-311/awscrt copying awscrt/common.py -> build/lib.linux-aarch64-cpython-311/awscrt copying awscrt/s3.py -> build/lib.linux-aarch64-cpython-311/awscrt copying awscrt/_test.py -> build/lib.linux-aarch64-cpython-311/awscrt copying awscrt/exceptions.py -> build/lib.linux-aarch64-cpython-311/awscrt copying awscrt/checksums.py -> build/lib.linux-aarch64-cpython-311/awscrt copying awscrt/http.py -> build/lib.linux-aarch64-cpython-311/awscrt copying awscrt/auth.py -> build/lib.linux-aarch64-cpython-311/awscrt copying awscrt/mqtt.py -> build/lib.linux-aarch64-cpython-311/awscrt copying awscrt/__init__.py -> build/lib.linux-aarch64-cpython-311/awscrt creating build/lib.linux-aarch64-cpython-311/awscrt/eventstream copying awscrt/eventstream/rpc.py -> build/lib.linux-aarch64-cpython-311/awscrt/eventstream copying awscrt/eventstream/__init__.py -> build/lib.linux-aarch64-cpython-311/awscrt/eventstream running build_ext Traceback (most recent call last): File "<string>", line 2, in <module> File "<pip-setuptools-caller>", line 34, in <module> File "/tmp/pip-install-akd5ijrb/awscrt_0517b812cd08420e9b83c9e0f620aaa8/setup.py", line 394, in <module> setuptools.setup( File "/usr/local/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup return distutils.core.setup(**attrs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup return run_commands(dist) ^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands dist.run_commands() File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands self.run_command(cmd) File "/usr/local/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command super().run_command(command) File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command cmd_obj.run() File "/usr/local/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 346, in run self.run_command("build") File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command self.distribution.run_command(command) File "/usr/local/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command super().run_command(command) File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command cmd_obj.run() File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 131, in run self.run_command(cmd_name) File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command self.distribution.run_command(command) File "/usr/local/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command super().run_command(command) File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command cmd_obj.run() File "/tmp/pip-install-akd5ijrb/awscrt_0517b812cd08420e9b83c9e0f620aaa8/setup.py", line 263, in run self._build_dependencies(dep_build_dir, dep_install_path) File "/tmp/pip-install-akd5ijrb/awscrt_0517b812cd08420e9b83c9e0f620aaa8/setup.py", line 255, in _build_dependencies self._build_dependencies_impl(build_dir, install_path) File "/tmp/pip-install-akd5ijrb/awscrt_0517b812cd08420e9b83c9e0f620aaa8/setup.py", line 163, in _build_dependencies_impl cmake = get_cmake_path() ^^^^^^^^^^^^^^^^ File "/tmp/pip-install-akd5ijrb/awscrt_0517b812cd08420e9b83c9e0f620aaa8/setup.py", line 122, in get_cmake_path raise Exception("CMake must be installed to build from source.") Exception: CMake must be installed to build from source. [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for awscrt ERROR: Could not build wheels for awscrt, which is required to install pyproject.toml-based projects [notice] A new release of pip is available: 23.1.2 -> 23.2.1 [notice] To update, run: pip install --upgrade pip

Unable to install package hatch_rest_api==1.20.8: error: subprocess-exited-with-error × python setup.py bdist_wheel did not run successfully. │ exit code: 1 ╰─> [68 lines of output] running bdist_wheel running build running build_py creating build creating build/lib.linux-aarch64-cpython-311 creating build/lib.linux-aarch64-cpython-311/awscrt copying awscrt/websocket.py -> build/lib.linux-aarch64-cpython-311/awscrt copying awscrt/io.py -> build/lib.linux-aarch64-cpython-311/awscrt copying awscrt/mqtt5.py -> build/lib.linux-aarch64-cpython-311/awscrt copying awscrt/crypto.py -> build/lib.linux-aarch64-cpython-311/awscrt copying awscrt/common.py -> build/lib.linux-aarch64-cpython-311/awscrt copying awscrt/s3.py -> build/lib.linux-aarch64-cpython-311/awscrt copying awscrt/_test.py -> build/lib.linux-aarch64-cpython-311/awscrt copying awscrt/exceptions.py -> build/lib.linux-aarch64-cpython-311/awscrt copying awscrt/checksums.py -> build/lib.linux-aarch64-cpython-311/awscrt copying awscrt/http.py -> build/lib.linux-aarch64-cpython-311/awscrt copying awscrt/auth.py -> build/lib.linux-aarch64-cpython-311/awscrt copying awscrt/mqtt.py -> build/lib.linux-aarch64-cpython-311/awscrt copying awscrt/__init__.py -> build/lib.linux-aarch64-cpython-311/awscrt creating build/lib.linux-aarch64-cpython-311/awscrt/eventstream copying awscrt/eventstream/rpc.py -> build/lib.linux-aarch64-cpython-311/awscrt/eventstream copying awscrt/eventstream/__init__.py -> build/lib.linux-aarch64-cpython-311/awscrt/eventstream running build_ext Traceback (most recent call last): File "<string>", line 2, in <module> File "<pip-setuptools-caller>", line 34, in <module> File "/tmp/pip-install-5oty9fo2/awscrt_9913cccbf7b543519ccc6ecc3f0f1556/setup.py", line 394, in <module> setuptools.setup( File "/usr/local/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup return distutils.core.setup(**attrs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup return run_commands(dist) ^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands dist.run_commands() File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands self.run_command(cmd) File "/usr/local/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command super().run_command(command) File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command cmd_obj.run() File "/usr/local/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 346, in run self.run_command("build") File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command self.distribution.run_command(command) File "/usr/local/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command super().run_command(command) File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command cmd_obj.run() File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 131, in run self.run_command(cmd_name) File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command self.distribution.run_command(command) File "/usr/local/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command super().run_command(command) File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command cmd_obj.run() File "/tmp/pip-install-5oty9fo2/awscrt_9913cccbf7b543519ccc6ecc3f0f1556/setup.py", line 263, in run self._build_dependencies(dep_build_dir, dep_install_path) File "/tmp/pip-install-5oty9fo2/awscrt_9913cccbf7b543519ccc6ecc3f0f1556/setup.py", line 255, in _build_dependencies self._build_dependencies_impl(build_dir, install_path) File "/tmp/pip-install-5oty9fo2/awscrt_9913cccbf7b543519ccc6ecc3f0f1556/setup.py", line 163, in _build_dependencies_impl cmake = get_cmake_path() ^^^^^^^^^^^^^^^^ File "/tmp/pip-install-5oty9fo2/awscrt_9913cccbf7b543519ccc6ecc3f0f1556/setup.py", line 122, in get_cmake_path raise Exception("CMake must be installed to build from source.") Exception: CMake must be installed to build from source. [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for awscrt ERROR: Could not build wheels for awscrt, which is required to install pyproject.toml-based projects [notice] A new release of pip is available: 23.1.2 -> 23.2.1 [notice] To update, run: pip install --upgrade pip
```

Appreciate all the hard work from everyone involved :)

**Comment by dahlb** [comment] 2023-08-23 00:58
this is a duplicate of https://github.com/dahlb/ha_hatch/issues/56 short version is it is an issue with aws not supporting your chosen platform there are a few work around listed in 56 though the simpliest is just to use version [1.15.5](https://github.com/dahlb/ha_hatch/releases/tag/v1.15.5) of ha_hatch

**Closed by dahlb** 2023-08-23 00:58 UTC
Labels: duplicate
