### ISSUE TITLE
won't load integration - 500 internal error

### ISSUE THREAD

**Issue by matchmee** [dahlb/ha_hatch#78] opened 2023-10-08 23:54 UTC
`2023-10-08 16:42:52.775 ERROR (SyncWorker_6) [homeassistant.util.package] Unable to install package hatch_rest_api==1.20.8: error: subprocess-exited-with-error`

Is what it says in the logs. The error I get on the popup when trying to install the integration:

`Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble`

I'm on 1.16.3 but haven't been able to get this integration to work since moving away from 15.6. I kept having that error that you told me to go backwards on the install, sometimes it works, sometimes it doesn't.

**Comment by matchmee** [comment] 2023-10-09 00:13
`Logger: homeassistant.util.package
Source: util/package.py:108
First occurred: 5:09:47 PM (3 occurrences)
Last logged: 5:11:44 PM

Unable to install package hatch_rest_api==1.20.8: error: subprocess-exited-with-error × python setup.py bdist_wheel did not run successfully. │ exit code: 1 ╰─> [68 lines of output] running bdist_wheel running build running build_py creating build creating build/lib.linux-armv7l-cpython-311 creating build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/crypto.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/auth.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/__init__.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/http.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/websocket.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/exceptions.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/mqtt.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/common.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/mqtt5.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/_test.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/io.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/checksums.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/s3.py -> build/lib.linux-armv7l-cpython-311/awscrt creating build/lib.linux-armv7l-cpython-311/awscrt/eventstream copying awscrt/eventstream/__init__.py -> build/lib.linux-armv7l-cpython-311/awscrt/eventstream copying awscrt/eventstream/rpc.py -> build/lib.linux-armv7l-cpython-311/awscrt/eventstream running build_ext Traceback (most recent call last): File "<string>", line 2, in <module> File "<pip-setuptools-caller>", line 34, in <module> File "/tmp/pip-install-1jbooyof/awscrt_efcba2a093244762a0957d3526984408/setup.py", line 394, in <module> setuptools.setup( File "/usr/local/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup return distutils.core.setup(**attrs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup return run_commands(dist) ^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands dist.run_commands() File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands self.run_command(cmd) File "/usr/local/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command super().run_command(command) File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command cmd_obj.run() File "/usr/local/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 364, in run self.run_command("build") File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command self.distribution.run_command(command) File "/usr/local/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command super().run_command(command) File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command cmd_obj.run() File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 131, in run self.run_command(cmd_name) File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command self.distribution.run_command(command) File "/usr/local/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command super().run_command(command) File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command cmd_obj.run() File "/tmp/pip-install-1jbooyof/awscrt_efcba2a093244762a0957d3526984408/setup.py", line 263, in run self._build_dependencies(dep_build_dir, dep_install_path) File "/tmp/pip-install-1jbooyof/awscrt_efcba2a093244762a0957d3526984408/setup.py", line 255, in _build_dependencies self._build_dependencies_impl(build_dir, install_path) File "/tmp/pip-install-1jbooyof/awscrt_efcba2a093244762a0957d3526984408/setup.py", line 163, in _build_dependencies_impl cmake = get_cmake_path() ^^^^^^^^^^^^^^^^ File "/tmp/pip-install-1jbooyof/awscrt_efcba2a093244762a0957d3526984408/setup.py", line 122, in get_cmake_path raise Exception("CMake must be installed to build from source.") Exception: CMake must be installed to build from source. [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for awscrt ERROR: Could not build wheels for awscrt, which is required to install pyproject.toml-based projects
Unable to install package hatch_rest_api==1.20.8: error: subprocess-exited-with-error × python setup.py bdist_wheel did not run successfully. │ exit code: 1 ╰─> [68 lines of output] running bdist_wheel running build running build_py creating build creating build/lib.linux-armv7l-cpython-311 creating build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/crypto.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/auth.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/__init__.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/http.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/websocket.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/exceptions.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/mqtt.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/common.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/mqtt5.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/_test.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/io.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/checksums.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/s3.py -> build/lib.linux-armv7l-cpython-311/awscrt creating build/lib.linux-armv7l-cpython-311/awscrt/eventstream copying awscrt/eventstream/__init__.py -> build/lib.linux-armv7l-cpython-311/awscrt/eventstream copying awscrt/eventstream/rpc.py -> build/lib.linux-armv7l-cpython-311/awscrt/eventstream running build_ext Traceback (most recent call last): File "<string>", line 2, in <module> File "<pip-setuptools-caller>", line 34, in <module> File "/tmp/pip-install-99_6m2au/awscrt_f59fec0134af41b2b7c50791f9068b76/setup.py", line 394, in <module> setuptools.setup( File "/usr/local/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup return distutils.core.setup(**attrs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup return run_commands(dist) ^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands dist.run_commands() File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands self.run_command(cmd) File "/usr/local/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command super().run_command(command) File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command cmd_obj.run() File "/usr/local/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 364, in run self.run_command("build") File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command self.distribution.run_command(command) File "/usr/local/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command super().run_command(command) File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command cmd_obj.run() File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 131, in run self.run_command(cmd_name) File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command self.distribution.run_command(command) File "/usr/local/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command super().run_command(command) File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command cmd_obj.run() File "/tmp/pip-install-99_6m2au/awscrt_f59fec0134af41b2b7c50791f9068b76/setup.py", line 263, in run self._build_dependencies(dep_build_dir, dep_install_path) File "/tmp/pip-install-99_6m2au/awscrt_f59fec0134af41b2b7c50791f9068b76/setup.py", line 255, in _build_dependencies self._build_dependencies_impl(build_dir, install_path) File "/tmp/pip-install-99_6m2au/awscrt_f59fec0134af41b2b7c50791f9068b76/setup.py", line 163, in _build_dependencies_impl cmake = get_cmake_path() ^^^^^^^^^^^^^^^^ File "/tmp/pip-install-99_6m2au/awscrt_f59fec0134af41b2b7c50791f9068b76/setup.py", line 122, in get_cmake_path raise Exception("CMake must be installed to build from source.") Exception: CMake must be installed to build from source. [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for awscrt ERROR: Could not build wheels for awscrt, which is required to install pyproject.toml-based projects
Unable to install package hatch_rest_api==1.20.8: error: subprocess-exited-with-error × python setup.py bdist_wheel did not run successfully. │ exit code: 1 ╰─> [68 lines of output] running bdist_wheel running build running build_py creating build creating build/lib.linux-armv7l-cpython-311 creating build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/crypto.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/auth.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/__init__.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/http.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/websocket.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/exceptions.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/mqtt.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/common.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/mqtt5.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/_test.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/io.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/checksums.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/s3.py -> build/lib.linux-armv7l-cpython-311/awscrt creating build/lib.linux-armv7l-cpython-311/awscrt/eventstream copying awscrt/eventstream/__init__.py -> build/lib.linux-armv7l-cpython-311/awscrt/eventstream copying awscrt/eventstream/rpc.py -> build/lib.linux-armv7l-cpython-311/awscrt/eventstream running build_ext Traceback (most recent call last): File "<string>", line 2, in <module> File "<pip-setuptools-caller>", line 34, in <module> File "/tmp/pip-install-2ux6uolc/awscrt_b9e07662efe043c1b973640257d9a413/setup.py", line 394, in <module> setuptools.setup( File "/usr/local/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup return distutils.core.setup(**attrs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup return run_commands(dist) ^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands dist.run_commands() File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands self.run_command(cmd) File "/usr/local/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command super().run_command(command) File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command cmd_obj.run() File "/usr/local/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 364, in run self.run_command("build") File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command self.distribution.run_command(command) File "/usr/local/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command super().run_command(command) File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command cmd_obj.run() File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 131, in run self.run_command(cmd_name) File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command self.distribution.run_command(command) File "/usr/local/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command super().run_command(command) File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command cmd_obj.run() File "/tmp/pip-install-2ux6uolc/awscrt_b9e07662efe043c1b973640257d9a413/setup.py", line 263, in run self._build_dependencies(dep_build_dir, dep_install_path) File "/tmp/pip-install-2ux6uolc/awscrt_b9e07662efe043c1b973640257d9a413/setup.py", line 255, in _build_dependencies self._build_dependencies_impl(build_dir, install_path) File "/tmp/pip-install-2ux6uolc/awscrt_b9e07662efe043c1b973640257d9a413/setup.py", line 163, in _build_dependencies_impl cmake = get_cmake_path() ^^^^^^^^^^^^^^^^ File "/tmp/pip-install-2ux6uolc/awscrt_b9e07662efe043c1b973640257d9a413/setup.py", line 122, in get_cmake_path raise Exception("CMake must be installed to build from source.") Exception: CMake must be installed to build from source. [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for awscrt ERROR: Could not build wheels for awscrt, which is required to install pyproject.toml-based projects
`

**Comment by dahlb** [comment] 2023-10-09 00:27
this is a duplicate of https://github.com/dahlb/ha_hatch/issues/56 short version is it is an issue with aws not supporting your chosen platform there are a few work around listed in 56 though the simpliest is just to use version [1.15.5](https://github.com/dahlb/ha_hatch/releases/tag/v1.15.5) of ha_hatch

**Closed by dahlb** 2023-10-09 00:27 UTC
