### ISSUE TITLE
Troubleshooting not working

### ISSUE THREAD

**Issue by tnfiberpilot** [dahlb/ha_hatch#154] opened 2024-07-31 03:18 UTC
I do encounter the problem mentioned of not being able to log in. The error says "needs attention" followed by "No devices or entities - Failed to set up: Check the logs".

Tried messing around with all the settings, restarting, and reloaded the entity all resulting in the same error. Any help would be great!

**Comment by dahlb** [comment] 2024-07-31 04:20
missing logs, follow the directions in the readme to enable verbose logs that will include all http traffic and any possible errors that occur. I can't help you with no logs provided

**Comment by tnfiberpilot** [comment] 2024-07-31 18:12
@dahlb my apologies.  Please see below.  I blanked my email for privacy.
Thank you!

Logger: homeassistant.config_entries
Source: config_entries.py:586
First occurred: July 30, 2024 at 10:57:32 PM (7 occurrences)
Last logged: July 30, 2024 at 11:11:30 PM

Error setting up entry XXX@gmail.com for ha_hatch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ha_hatch/__init__.py", line 105, in async_setup_entry
    await setup_connection("initial setup")
  File "/config/custom_components/ha_hatch/__init__.py", line 77, in setup_connection
    _, mqtt_connection, rest_devices, expiration_time = await get_rest_devices(
                                                        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hatch_rest_api/util_bootstrap.py", line 71, in get_rest_devices
    raise e
  File "/usr/local/lib/python3.12/site-packages/hatch_rest_api/util_bootstrap.py", line 67, in get_rest_devices
    await loop.run_in_executor(None, connect_future.result)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
awscrt.exceptions.AwsCrtError: AWS_ERROR_MQTT_UNEXPECTED_HANGUP: The connection was closed unexpectedly.

**Comment by dahlb** [comment] 2024-07-31 20:39
thanks for the logs, the details make this a duplicate of https://github.com/dahlb/ha_hatch/issues/10 there are multiple causes on this error, some discovered some still unknown

**Closed by dahlb** 2024-07-31 20:39 UTC
