### ISSUE TITLE
Error: Config flow could not be loaded undefined

### ISSUE THREAD

**Issue by jamescadd** [dahlb/ha_hatch#6] opened 2022-09-05 23:41 UTC
I installed via HACS on latest Home Assistant version, went to integrations and tried to add this one. I receive the error that the config flow could not be loaded, there are no prompts to login. I have not made any edits to config.yaml as it wasn't suggested in the readme.

I'm using Hatch Rest+ if that matters. Thanks for adding support for this device btw, looking forward to using the integration!

**Comment by dahlb** [comment] 2022-09-05 23:53
sorry this is a duplicate of https://github.com/dahlb/ha_hatch/issues/5, quick summary two upstream issues either of which would fix this https://github.com/awslabs/aws-crt-python/issues/315 and https://github.com/home-assistant/wheels-custom-integrations/pull/595

**Closed** 2022-09-05 23:53 UTC
Labels: duplicate

**Comment by jamescadd** [comment] 2022-09-06 00:01
Ok thanks for the background! Is there any workaround until one of those is closed? In the other thread it seems people are using HomeBridge integration instead
